development:
  cloud_name: hveym2j49
  api_key: '592916926866421'
  api_secret: jcUJ1IZx6omSw3NnrsE8yUqaa1A
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hveym2j49
  api_key: '592916926866421'
  api_secret: jcUJ1IZx6omSw3NnrsE8yUqaa1A
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hveym2j49
  api_key: '592916926866421'
  api_secret: jcUJ1IZx6omSw3NnrsE8yUqaa1A
  enhance_image_tag: true
  static_image_support: false
