---
development:
  cloud_name: hdmqoteej
  api_key: '831529458453272'
  api_secret: cnt1Ew_4h3UPB2i-nha0KF-ywYY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hdmqoteej
  api_key: '831529458453272'
  api_secret: cnt1Ew_4h3UPB2i-nha0KF-ywYY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hdmqoteej
  api_key: '831529458453272'
  api_secret: cnt1Ew_4h3UPB2i-nha0KF-ywYY
  enhance_image_tag: true
  static_image_support: false
